config/routes.rb
Cleanfb::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, param: :id do
    member do
      get :fetch_friends
    end
  end

  resources :dashboard
  resources :friendships do
    member do
      post :add_friend
    end
  end

  resources :conversations do
    resources :messages
  end

  resources :users
  root 'dashboard#index'

  

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
  has_many :messages
  validates_uniqueness_of :sender_id, :scope => :recipient_id

  # Write two scopes for involving and between cases for fetching converstations
  # Involving is for listing all the conversationss of the user.
  # Between if for triggering the conversationss in b/w 2 users
  # between scope can will fetch for any conversation which has sender_id and recipient_id matching.
  scope :between, -> (sender_id, recipient_id) do
    where("(conversations.sender_id=? AND conversations.recipient_id=?) OR (conversations.sender_id=? AND conversations.recipient_id=?)",sender_id, recipient_id, recipient_id, sender_id)
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  layout false
  
  # This can be a central controller to handle all the chat related routing functionality
  # not necessarilly a conversations thing
  # Create a conversation object
  def create

=begin 
    if Conversation.between(params[:sender_id], params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else # If conversation is not present
      @conversation = Conversation.create!(conversation_params)
    end
=end
    sender_id = params[:sender_id]
    recipient_id = params[:recipient_id]
    
    @conversation = MessagingService::Message.
                      get_conversation(
                        sender_id: sender_id, 
                        recipient_id: recipient_id, 
                        conversation_params: params
                      ).conversation
    render json: { conversation_id: @conversation.id }
  end

  def show
    # @conversation = Conversation.find(params[:id])
    # get conversation from Messeging service
    @conversation = MessagingService::Message.
                      get_conversation(
                        conversation_id: params[:id]
                      ).conversation
    # @reciever = interlocutor(@conversation)
    @reciever = new_interlocutor(@conversation)
    # @messages = @conversation.messages 
    @messages = MessagingService::Message.
                 get_messages_from_conversation(
                   conversation_id: @conversation.id
                 ).messages
    @message = Message.new  # find an alternative for this.
  end

  private
=begin
  def conversation_params
    params.permit(:sender_id, :recipient_id)
  end
  

  def interlocutor(conversation)
    current_user = conversation.recipient ? conversation.sender : conversation.recipient
  end
=end

  def new_interlocutor(conversation)
    if current_user.id.eql?(conversation.sender_id)
      return User.find(conversation.recipient_id)
    else
      return User.find(conversation.sender_id)
    end
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/show.html.erb
<div class="chatboxhead">
  <div class="chatboxtitle">
    <i class="fa fa-comments"></i>
     
    <h1><%= @reciever.name %> </h1>
  </div>
  <div class="chatboxoptions">
    <%= link_to "<i class='fa fa-minus'></i> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id %>
    &nbsp;&nbsp;
    <%= link_to "<i class='fa fa-times'></i> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id %>
  </div>
  <br clear="all"/>
</div>
<div class="chatboxcontent">
  <% if @messages.any? %>
    <%= render "/messages/message", collection: @messages %>
  <% end %>
</div>

<%#= binding.pry %>
<div class="chatboxinput">
  <%= form_for(@message, :url => conversation_messages_path(@conversation.id) ,:remote => true, :html => {id: "conversation_form_#{@conversation.id}"}) do |f| %>
    <%= f.text_area :body, class: "chatboxtextarea", "data-cid" => @conversation.id %>
  <% end %>
</div>
<!-- TODO faye subscribe hook not working at present find sollution -->
<%#= subscribe_to conversation_path(@conversation) %> 